export default {
  MENU_TOGGLE: "navigation/toggle",
  FETCH_MOVIES_REQUEST: "fetch/movies/request",
  FETCH_MOVIES_SUCCESS: "fetch/movies/success",
  FETCH_MOVIES_ERROR: "fetch/movies/error",
  FETCH_MOVIE_DETAILS_REQUEST: "fetch/movie-details/request",
  FETCH_MOVIE_DETAILS_SUCCESS: "fetch/movie-details/success",
  FETCH_MOVIE_DETAILS_ERROR: "fetch/movie-details/error",
  LOGIN_REQUEST: "session/login/request",
  LOGIN_SUCCESS: "session/login/success",
  LOGIN_ERROR: "session/login/error",
  SIGNUP_REQUEST: "session/signup/request",
  SIGNUP_SUCCESS: "session/signup/success",
  SIGNUP_ERROR: "session/signup/error",
  LOGOUT: "session/logout",
};
